apiVersion: v1
kind: ConfigMap
metadata:
  # If you want to use this config map by default, name it "artifact-repositories". Otherwise, you can provide a reference to a
  # different config map in `artifactRepositoryRef.configMap`.
  name: artifact-repositories
  annotations:
    # v3.0 and after - if you want to use a specific key, put that key into this annotation.
    workflows.argoproj.io/default-artifact-repository: default-v1-s3-artifact-repository
data:
  default-v1-s3-artifact-repository: |
    s3:
      endpoint: minio-service:9000
      bucket: argobucket
      accessKeySecret:
        key: accesskey
        name: argo-artifacts
      secretKeySecret:
        key: secretkey
        name: argo-artifacts
      insecure: true
